<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="12900" started-at="2016-06-07T03:42:01Z" finished-at="2016-06-07T03:42:14Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="12900" started-at="2016-06-07T03:42:01Z" finished-at="2016-06-07T03:42:14Z">
      <class name="com.test.DataDrivenFramework.DataDrivenDemo">
        <test-method status="FAIL" signature="loginDemo(java.lang.String, java.lang.String)[pri:0, instance:com.test.DataDrivenFramework.DataDrivenDemo@5034c75a]" name="loginDemo" duration-ms="4004" started-at="2016-06-06T22:42:01Z" data-provider="loginData" finished-at="2016-06-06T22:42:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[savanth]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[demo123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.DataDrivenFramework.DataDrivenDemo.loginDemo(DataDrivenDemo.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginDemo -->
        <test-method status="PASS" signature="driverQuit()[pri:0, instance:com.test.DataDrivenFramework.DataDrivenDemo@5034c75a]" name="driverQuit" is-config="true" duration-ms="91" started-at="2016-06-06T22:42:05Z" finished-at="2016-06-06T22:42:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverQuit -->
        <test-method status="FAIL" signature="loginDemo(java.lang.String, java.lang.String)[pri:0, instance:com.test.DataDrivenFramework.DataDrivenDemo@5034c75a]" name="loginDemo" duration-ms="2818" started-at="2016-06-06T22:42:05Z" data-provider="loginData" finished-at="2016-06-06T22:42:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[savanth.ch@gmail]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Nanu123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.DataDrivenFramework.DataDrivenDemo.loginDemo(DataDrivenDemo.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginDemo -->
        <test-method status="PASS" signature="driverQuit()[pri:0, instance:com.test.DataDrivenFramework.DataDrivenDemo@5034c75a]" name="driverQuit" is-config="true" duration-ms="95" started-at="2016-06-06T22:42:08Z" finished-at="2016-06-06T22:42:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverQuit -->
        <test-method status="PASS" signature="loginDemo(java.lang.String, java.lang.String)[pri:0, instance:com.test.DataDrivenFramework.DataDrivenDemo@5034c75a]" name="loginDemo" duration-ms="5738" started-at="2016-06-06T22:42:08Z" data-provider="loginData" finished-at="2016-06-06T22:42:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[savanth.ch@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Nanu@8113]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginDemo -->
        <test-method status="PASS" signature="driverQuit()[pri:0, instance:com.test.DataDrivenFramework.DataDrivenDemo@5034c75a]" name="driverQuit" is-config="true" duration-ms="123" started-at="2016-06-06T22:42:14Z" finished-at="2016-06-06T22:42:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverQuit -->
      </class> <!-- com.test.DataDrivenFramework.DataDrivenDemo -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
